apiKeys:
  - a
  - b
  - couldBeOneOrMore
  - reallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylongreallylong
listenPort: 80
mongoDb:
  connectionString: "mongodb://localhost:27017"
  targetCollection: "auditlogs"